feat: 카카오 로그인 기능 구현
ssafy-pjt-naem/naem-back pull request #46
Opened 2024-06-19 05:20 UTC by chwangmin

#45 , #39 CORS, kakao 로그인 기능을 구현하였습니다.

2024-06-25 05:48 UTC, bjho606 commented on src/main/java/com/ssafy/naem/domain/login/dto/request/OauthLoginRequest.java
> +@Setter
Setter 지워주세요

2024-06-25 05:48 UTC, bjho606 commented on src/main/java/com/ssafy/naem/domain/login/dto/response/OauthLoginResponse.java
> +@Setter
Setter 지워주세요

2024-06-25 06:04 UTC, bjho606 reviewed
setter 빼기, 컬럼 변경 사항 반영, 예외 처리 형식 처리하면 될것 같습니다.

2024-06-25 06:04 UTC, bjho606 commented on src/main/java/com/ssafy/naem/domain/oauth/validator/AuthorizationHeaderUtils.java
이번에 머지된 BaseResponseStatus에 에러 추가해서 exception 처리해보면 어떨까요?

2024-06-25 06:04 UTC, bjho606 commented on src/main/java/com/ssafy/naem/domain/oauth/validator/OauthValidator.java
이번에 머지된 BaseResponseStatus에 에러 추가해서 exception 처리해보면 어떨까요?

2024-06-25 06:25 UTC, minju412 requested changes
고생하셨습니다!!👍👍

2024-06-25 06:25 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/oauth/kakao/dto/request/KakaoTokenRequest.java
> +    }
기존 코드는 `@Builder`를 생성자에 적용했는데, 빌더 패턴 사용 시 특별한 로직이 필요하지 않다면 아래 코드처럼 클래스 수준에 적용하는 것도 고려해보면 좋을 것 같아요. 코드가 깔끔해집니당 

```java
@NoArgsConstructor
@Getter
@Builder
public class KakaoTokenRequest {
    private String grant_type;
    private String client_id;
    private String redirect_uri;
    private String code;
    private String client_secret;
}
```

2024-06-25 06:25 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/oauth/kakao/dto/response/KakaoTokenResponse.java
> +        @Builder
위와 마찬가지 의견입니다!

2024-06-25 06:25 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/oauth/kakao/dto/response/KakaoUserInfoResponse.java
> +@Getter @Setter
Setter 제거해주세욥!

2024-06-25 06:25 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/oauth/validator/OauthValidator.java
> +@Service
validation의 경우, 함께 고민해볼 가치가 있다고 생각합니다!

1. validator를 별도의 서비스로 정의 (지금 방법!)
  a. 책임 분리 원칙을 따르는 좋은 객체지향 설계 방식이지만, 작은 규모의 프로젝트에서는 불필요한 종속성을 높일 수 있습니다.
2. 컨트롤러에서 바로 검증
3. 서비스에서 검증
4. 도메인 객체에서 검증
  a. 검증 로직을 도메인 객체 내에 포함시킴으로써, 도메인 객체의 상태가 항상 유효하도록 강제할 수 있습니다.
5. 커스텀 Valid Annotation 만들기 [참고](https://shinsunyoung.tistory.com/89)

여러 방법 중 1번 방법을 선택하게 된 이유가 있는지 고민해보면 좋을 것 같아요!

2024-06-25 06:35 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/member/entity/Member.java
> +    @Column(name = "name", nullable = false, length = 20)
jpa에서 지원는 Column을 통해 name이 변수 명에 따라 default로 설정되어 명시하지 않아도 되군요.
저는 name을 직접 지정함으로써, sql에 연결된 변수가 무엇인지 명확히 알 수 있어 추가했습니다.

2024-06-25 07:00 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/login/respository/MemberRepository.java
> +    Optional<Member> findByEmail(@Param("email") String email);
아차 이건 몰랐네요. 알려주셔서 감사합니다. 삭제할게요

2024-06-25 07:08 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/oauth/dto/response/OAuthAttributeResponse.java
> +    public Member toMemberEntity() {
MapStruct를 사용해서 리플랙션 없이 Entity to Dto 변경 코드로 수정해볼게요!

2024-06-25 07:09 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/member/entity/Member.java
제가 구현할 코드 부분이 아니라, 임시로 만든 거라 검토를 못했네요. 다시 수정할게요!

2024-06-25 07:10 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/oauth/validator/AuthorizationHeaderUtils.java
merge 할 branch에 BaseResponse 코드가 존재하는 걸로 알고 있어서, merge 후에 다시 refactoring 하면서 수정할게요!

2024-06-25 07:12 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/login/dto/response/OauthLoginResponse.java
> +@Setter
Setter로 인해 불변성, 캡슐화, update or create 인지 모호성이 있기에 삭제를 해야 했는 데 검토를 못했네요, 다 지울게요!

2024-06-25 08:01 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/oauth/kakao/dto/request/KakaoTokenRequest.java
> +    }
@Builder를 추가해서 수정하려고 했습니다.
하지만 기본 생성자(접근 제한 속성)가 존재해서 문제가 발생하여서
모든 파라미터로 가지는 @AllArgsConstructor을 추가하여 해결했어요

2024-06-26 06:51 UTC, minju412 approved these changes
굳굳입니다 👍👍

2024-06-26 07:07 UTC, merged