Feature: board api #42
ssafy-pjt-naem/naem-back pull request #47
Opened 2024-06-20 07:35 UTC by bjho606

close #42

2024-06-20 07:46 UTC, chwangmin reviewed
수정부탁드립니다~

2024-06-20 07:46 UTC, chwangmin commented on src/main/java/com/ssafy/naem/config/secret/Secret.java
민감한 정보 삭제해주세요 ~

2024-06-20 07:46 UTC, chwangmin commented on src/main/java/com/ssafy/naem/domain/board/repository/BoardRepository.java
필요없는 주석 삭제해주세요~

2024-06-20 08:00 UTC, chwangmin approved these changes
board api 테스트 코드까지 짜시느라 고생많으셨습니다!!

2024-06-20 08:07 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/board/controller/BoardController.java
> +            return new BaseResponse<>(boardService.getAllActiveBoards());
컨트롤러 단에서 모든 로직에 try~catch를 하고 있는데, 조금 더 고민해봅시다..!!

2024-06-20 08:13 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/board/entity/Board.java
> +    @PrePersist
제 코드에서 이 부분(생성, 수정일 갱신)을 BaseTimeEntity로 따로 정의해뒀으니 머지하고 수정하면 좋을 것 같아요!

2024-06-20 08:20 UTC, minju412 requested changes
테스트코드까지 대단하네요👍 수정 후 다시 봅시다~!

2024-06-21 07:56 UTC, bjho606 commented on src/main/java/com/ssafy/naem/domain/board/controller/BoardController.java
> +            return new BaseResponse<>(boardService.getAllActiveBoards());
ControllerAdvice로 처리 완료!

2024-06-21 07:59 UTC, minju412 commented on src/main/java/com/ssafy/naem/domain/board/service/BoardService.java
> +        String newName = boardChangeNameRequest.name();
recored 문법 신기하네요👍

2024-06-21 08:01 UTC, minju412 approved these changes
Controller Advice까지 적용하느라 고생하셨습니다 👍👍

2024-06-21 08:06 UTC, chwangmin approved these changes
고생하셨습니다~

2024-06-21 08:06 UTC, merged